### ISSUE TITLE
homebridge "Cannot find module 'node-fetch'" error at startup when using homebridge-yamaha-avr

### ISSUE THREAD

**Issue by jamesmulcahy** [ACDR/homebridge-yamaha-avr#1]
The module installs OK, but at runtime it depends on node-fetch, which doesn't appear to be an explicit dependency.  If I manually install node-fetch too, then it initializes OK.

```
[3/19/2019, 9:47:50 PM] Loaded plugin: homebridge-yamaha
[3/19/2019, 9:47:50 PM] Registering accessory 'homebridge-yamaha.YamahaAVR'
[3/19/2019, 9:47:50 PM] Registering platform 'homebridge-yamaha.YamahaAVR'
[3/19/2019, 9:47:50 PM] ---
[3/19/2019, 9:47:50 PM] ====================
[3/19/2019, 9:47:50 PM] ERROR LOADING PLUGIN homebridge-yamaha-avr:
[3/19/2019, 9:47:50 PM] Error: Cannot find module 'node-fetch'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/homebridge/node_modules/homebridge-yamaha-avr/index.js:2:15)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Plugin.load (/usr/local/lib/node_modules/homebridge/lib/plugin.js:72:23)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:149:14)
    at Array.forEach (<anonymous>)
    at Server._loadPlugins (/usr/local/lib/node_modules/homebridge/lib/server.js:141:22)
```

**Comment by ACDR** [comment]
@jamesmulcahy - added node-fetch dependency, thanks!
