### ISSUE TITLE
Issue with Multiple Yamaha AVRs

### ISSUE THREAD

**Issue by alexargo** [ACDR/homebridge-yamaha-avr#10]
I have two Yamaha TSR-7850s(Hey... they were on sale at Costco.....) and am getting the following error when trying to boot up home bridge:

These seems to crash home bridge and put it in a very strange state similar to #9 

`[8/15/2019, 11:03:03 PM] Homebridge is running on port 51826.
[8/15/2019, 11:03:03 PM] [yamaha-zone-tv] Possible Yamaha device discovered Diskstation [ 'fe80::211:32ff:fe33:1601', '192.168.1.47' ]
[8/15/2019, 11:03:03 PM] [yamaha-zone-tv] Possible Yamaha device discovered Basement [ '192.168.1.110', 'fe80::4e1b:86ff:fe89:68aa' ]
[8/15/2019, 11:03:03 PM] [yamaha-zone-tv] Possible Yamaha device discovered Patio [ '192.168.1.74', 'fe80::4e1b:86ff:fea6:3d6a' ]
[8/15/2019, 11:03:03 PM] [yamaha-zone-tv] Found Yamaha TSR-7850 - 03D38A63, "Patio"
[8/15/2019, 11:03:03 PM] [yamaha-zone-tv] Found Yamaha TSR-7850 - 06402303, "Basement"
[8/15/2019, 11:03:03 PM] [yamaha-zone-tv] Possible Yamaha device discovered EPSON XP-820 Series [ '192.168.1.54', 'fe80::66eb:8cff:fe13:ac1f' ]
[8/15/2019, 11:03:03 PM] [yamaha-zone-tv] Adding TV Control for Main
[8/15/2019, 11:03:03 PM] [yamaha-zone-tv] Adding TV Control for Zone2
Unhandled rejection Error: Cannot add a Service with the same UUID '000000D9-0000-1000-8000-0026BB765291' and subtype '15eb8e46-3ee2-4b1e-922a-366be0895315' as another Service in this Accessory.
    at PlatformAccessory.addService (/usr/local/lib/node_modules/homebridge/lib/platformAccessory.js:55:15)
    at YamahaZone.<anonymous> (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/index.js:547:24)
    at Array.forEach (<anonymous>)
    at YamahaZone.getServices (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/index.js:519:12)
    at YamahaAVRPlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/index.js:198:37)
    at tryCatcher (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:699:18)
    at Promise._fulfill (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:643:18)
    at Promise._resolveCallback (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:459:14)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:529:17)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._fulfillPromises (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:674:14)
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:700:18)
    at Promise._fulfill (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:643:18)
    at Promise._resolveCallback (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:437:57)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:529:17)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:699:18)
    at Promise._fulfill (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:643:18)
    at Promise._resolveCallback (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:437:57)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:529:17)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:699:18)
    at Promise._fulfill (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:643:18)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/timers.js:26:46)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
[8/15/2019, 11:03:04 PM] [yamaha-zone-tv] Adding TV Control for Main
[8/15/2019, 11:03:04 PM] [yamaha-zone-tv] Adding TV Control for Zone2
Unhandled rejection Error: Cannot add a Service with the same UUID '000000D9-0000-1000-8000-0026BB765291' and subtype '15eb8e46-3ee2-4b1e-922a-366be0895315' as another Service in this Accessory.
    at PlatformAccessory.addService (/usr/local/lib/node_modules/homebridge/lib/platformAccessory.js:55:15)
    at YamahaZone.<anonymous> (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/index.js:547:24)
    at Array.forEach (<anonymous>)
    at YamahaZone.getServices (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/index.js:519:12)
    at YamahaAVRPlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/index.js:198:37)
    at tryCatcher (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:699:18)
    at Promise._fulfill (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:643:18)
    at Promise._resolveCallback (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:459:14)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:529:17)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._fulfillPromises (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:674:14)
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:700:18)
    at Promise._fulfill (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:643:18)
    at Promise._resolveCallback (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:437:57)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:529:17)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:699:18)
    at Promise._fulfill (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:643:18)
    at Promise._resolveCallback (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:437:57)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:529:17)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:699:18)
    at Promise._fulfill (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:643:18)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/timers.js:26:46)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)`

**Comment by alexargo** [comment]
Whoops wrong plugin
