### ISSUE TITLE
Unhandled rejection TypeError: Service.Television is not a constructor

### ISSUE THREAD

**Issue by jamesmulcahy** [ACDR/homebridge-yamaha-avr#2]
I get this error at startup.

```
Unhandled rejection TypeError: Service.Television is not a constructor
    at YamahaAVRAccessory.televisionService (/homebridge/node_modules/homebridge-yamaha-avr/index.js:112:20)
    at YamahaAVRAccessory.getServices (/homebridge/node_modules/homebridge-yamaha-avr/index.js:89:8)
    at Server._createAccessory (/usr/local/lib/node_modules/homebridge/lib/server.js:410:36)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:396:32)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:16:19
    at YAMAHA.getSystemConfig.then (/homebridge/node_modules/homebridge-yamaha-avr/index.js:31:11)
    at tryCatcher (/homebridge/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/homebridge/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/homebridge/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/homebridge/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/homebridge/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill (/homebridge/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/homebridge/node_modules/bluebird/js/release/promise.js:454:14)
    at Promise._settlePromiseFromHandler (/homebridge/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/homebridge/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._fulfillPromises (/homebridge/node_modules/bluebird/js/release/promise.js:669:14)
[3/19/2019, 9:49:24 PM] [mqtt] A new version 0.5.1 is avaiable
```

The yamaha section of my config looks like:

```
{
                    "platform": "yamaha-avr",
                    "name": "Yamaha RX-V675",
                    "ip": "192.168.1.190",
                    "inputs": [
                            {
                                    "id": "HDMI2",
                                    "name": "Apple TV"
                            },
                            {
                                    "id": "HDMI3",
                                    "name": "Dish"
                            }
                    ]
            }
```

**Comment by ACDR** [comment]
@jamesmulcahy - what version of Homebridge are you currently running? You will need to be running the latest release, currently v0.4.46 for TV Accessory support.

**Comment by jamesmulcahy** [comment]
Ah, that was it -- my bad! I thought I'd pulled the latest version, but it was an old cached version. Thanks for the prompt reply!
