### ISSUE TITLE
ReferenceError: log is not defined

### ISSUE THREAD

**Issue by jamesmulcahy** [ACDR/homebridge-yamaha-avr#3]
The homebridge-yamaha-avr module is causing homebridge to restart when it throws this error:

```
/homebridge/node_modules/homebridge-yamaha-avr/index.js:167
          log('CREATED INPUT:', value);
          ^

ReferenceError: log is not defined
    at Characteristic.ConfiguredName.inputService.getCharacteristic.on (/homebridge/node_modules/homebridge-yamaha-avr/index.js:167:11)
    at Characteristic.ConfiguredName.emit (events.js:189:13)
    at Characteristic.ConfiguredName.Characteristic.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:321:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:873:22)
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._handleSetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:813:8)
    at HAPServer.emit (events.js:189:13)
    at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:972:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at IncomingMessage.emit (events.js:189:13)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by ACDR** [comment]
@jamesmulcahy - odd, that line isn't throwing an error for me, though it clearly should. I've removed the log in any case. Let me know how you get on!
