### ISSUE TITLE
Homebridge crash if Yamaha AVR not found (EHOSTUNREACH)

### ISSUE THREAD

**Issue by rg2k** [ACDR/homebridge-yamaha-avr#9]
This plugin crashes Homebridge and forces failure loop when the Yamaha AVR network cable is physically disconnected or receives a new IP from DHCP.

Error:
[7/9/2019, 7:32:43 AM] [Yamaha RX-V685] ERROR: Failed getSystemConfig from Yamaha RX-V685 probably just not a Yamaha AVR. { Error: connect EHOSTUNREACH 192.168.1.203:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
  cause:
   { Error: connect EHOSTUNREACH 192.168.1.203:80
       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
     errno: 'EHOSTUNREACH',
     code: 'EHOSTUNREACH',
     syscall: 'connect',
     address: '192.168.1.203',
     port: 80 },
  isOperational: true,
  errno: 'EHOSTUNREACH',
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '192.168.1.203',
  port: 80 }

The plugin should catch the error and handle it without stopping Homebridge.

**Comment by Kienz** [comment]
Fatal TypeError: Cannot set property 'getVolume' of null                                                                                                                                                                                                                                                                                                                                          
    at enrichBasicStatus (/usr/local/lib/node_modules/homebridge-yamaha-avr/node_modules/yamaha-nodejs/simpleCommands.js:354:27)                                                                                                                                                                                                                                                                  
    at /usr/local/lib/node_modules/homebridge-yamaha-avr/node_modules/yamaha-nodejs/simpleCommands.js:345:16                                                                                                                                                                                                                                                                                      
    at tryCatcher (/usr/local/lib/node_modules/homebridge-yamaha-avr/node_modules/bluebird/js/release/util.js:16:23)                                                                                                                                                                                                                                                                              
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-yamaha-avr/node_modules/bluebird/js/release/promise.js:547:31)                                                                                                                                                                                                                                                   
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-yamaha-avr/node_modules/bluebird/js/release/promise.js:604:18)                                                                                                                                                                                                                                                              
    at Promise._settlePromise0 (/usr/local/lib/node_modules/homebridge-yamaha-avr/node_modules/bluebird/js/release/promise.js:649:10)                                                                                                                                                                                                                                                             
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-yamaha-avr/node_modules/bluebird/js/release/promise.js:729:18)                                                                                                                                                                                                                                                             
    at Promise._fulfill (/usr/local/lib/node_modules/homebridge-yamaha-avr/node_modules/bluebird/js/release/promise.js:673:18)                                                                                                                                                                                                                                                                    
    at Promise._resolveCallback (/usr/local/lib/node_modules/homebridge-yamaha-avr/node_modules/bluebird/js/release/promise.js:489:14)                                                                                                                                                                                                                                                            
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-yamaha-avr/node_modules/bluebird/js/release/promise.js:559:17)                                                                                                                                                                                                                                                   
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-yamaha-avr/node_modules/bluebird/js/release/promise.js:604:18)                                                                                                                                                                                                                                                              
    at Promise._fulfillPromises (/usr/local/lib/node_modules/homebridge-yamaha-avr/node_modules/bluebird/js/release/promise.js:704:14)                                                                                                                                                                                                                                                            
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-yamaha-avr/node_modules/bluebird/js/release/promise.js:730:18)                                                                                                                                                                                                                                                             
    at Promise._fulfill (/usr/local/lib/node_modules/homebridge-yamaha-avr/node_modules/bluebird/js/release/promise.js:673:18)                                                                                                                                                                                                                                                                    
    at Promise._resolveCallback (/usr/local/lib/node_modules/homebridge-yamaha-avr/node_modules/bluebird/js/release/promise.js:466:57)                                                                                                                                                                                                                                                            
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-yamaha-avr/node_modules/bluebird/js/release/promise.js:559:17)

**Comment by Kienz** [comment]
Any news?

**Comment by ACDR** [comment]
> Any news?

Looking into this now

**Comment by Kienz** [comment]
Now I have all inputs that are available - before the update 1.0.1 I only have the defined inputs show below.

```json
    "inputs": [{
        "id": "HDMI3",
        "name": "Apple TV"
      }, {
        "id": "AUDIO2",
        "name": "Sonos"
      }, {
        "id": "HDMI2",
        "name": "Sky"
      }, {
        "id": "HDMI1",
        "name": "Playstation"
      }, {
        "id": "Bluetooth",
        "name": "Bluetooth"
      }, {
        "id": "NET RADIO",
        "name": "Internet-Radio"
      }]
```

**Comment by Kienz** [comment]
Still crashing if receiver is complete powered off.

```
 Error: connect EHOSTUNREACH 192.168.1.18:80                                                                                                                                                                                                                
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)                                                                                                                                                                                          
  cause:                                                                                                                                                                                                                                                     
   { Error: connect EHOSTUNREACH 192.168.1.18:80                                                                                                                                                                                                             
       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)                                                                                                                                                                                       
     errno: 'EHOSTUNREACH',                                                                                                                                                                                                                                  
     code: 'EHOSTUNREACH',                                                                                                                                                                                                                                   
     syscall: 'connect',                                                                                                                                                                                                                                     
     address: 'x.x.x.x',                                                                                                                                                                                                                                
     port: 80 },                                                                                                                                                                                                                                             
  isOperational: true,                                                                                                                                                                                                                                       
  errno: 'EHOSTUNREACH',                                                                                                                                                                                                                                     
  code: 'EHOSTUNREACH',                                                                                                                                                                                                                                      
  syscall: 'connect',                                                                                                                                                                                                                                        
  address: 'x.x.x.x',                                                                                                                                                                                                                                   
  port: 80 }             
```

**Comment by ACDR** [comment]
> Still crashing if receiver is complete powered off.

Just throwing the error or crashing homebridge completely?

**Comment by Kienz** [comment]
It crashes Homebridge completely.

**Comment by ACDR** [comment]
> It crashes Homebridge completely.

If you could try again with `1.0.3` and let me know if you have any luck that would be much appreciated. May have just been pulling an older version of `yamaha-nodejs`.

In my own testing it logs out the `EHOSTUNREACH` error if the receiver connection is lost but doesn't crash Homebridge completely.

**Comment by rg2k** [comment]
> > It crashes Homebridge completely.
> 
> If you could try again with `1.0.3` and let me know if you have any luck that would be much appreciated. May have just been pulling an older version of `yamaha-nodejs`.
> 
> In my own testing it logs out the `EHOSTUNREACH` error if the receiver connection is lost but doesn't crash Homebridge completely.

I did a quick test with an incorrect IP and it no longer crashes on HomeBridge startup. It does, however, log out the error every 3 seconds - but that is much better than a crash :-)

**Comment by Kienz** [comment]
I got every 3 seconds the error message but Homebridge did not crash. After power on the outlet (yamaha avr is still powered off), I got the following error and Homebridge crashes completly.
```
[1/12/2020, 6:18:46 PM] [Yamaha AVR] Failed to get available inputs from Yamaha AVR. Please verify the AVR is connected and accessible at 19
2.168.1.18                                                                                                                                  
Fatal Error: connect EHOSTUNREACH 192.168.1.18:80                                                                                           
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)   
```

**Comment by Kienz** [comment]
And If the Yamaha AVR is not powered on (outlet is powered on) the Yamaha AVR accessory is missing after Homebridge reboot. It appears only If the Yamaha AVR is powered on after reboot.

**Comment by recom273** [comment]
OperationalError: connect ETIMEDOUT 192.168.68.105:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
 {
  cause: Error: connect ETIMEDOUT 192.168.68.105:80
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
   {
    errno: 'ETIMEDOUT',
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '192.168.68.105',
    port: 80
  },

Yeah, same issues with me - it doesn't seem to crash Homebridge but it does seem to be causing 'not responding' - if I remove the plugin, everything is fine.

Config

 {
            "platform": "yamaha-avr",
            "name": "Yamaha RX-V581",
            "ip": "192.168.68.105",
            "inputs": [
                {
                    "id": "AUDIO1",
                    "name": "Samsung TV"
                },
                {
                    "id": "AV4",
                    "name": "Volumio"
                },
                {
                    "id": "HDMI1",
                    "name": "BD Player"
                },
                {
                    "id": "HDMI2",
                    "name": "Yamaha AVR"
                }
            ]
        },

**Comment by ACDR** [comment]
This has been fixed in the beta release:
https://github.com/ACDR/homebridge-yamaha-avr/releases/tag/v2.0.0-beta.1

`npm install -g homebridge-yamaha-avr@beta`
